language: php
php:
- 7.1
- 7.2
- 7.3
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=latest
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh pbt_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: lQqgkF00ZhWUmHDBUFJcSoYJnVbSqZ9GWI7RZM9aFTl4gkgVhKIM9pAhuxfaDGLTx9fruw53Vg7d1W5me9qayweb5npf41IHndXQ1xtFKuDnsb8VZnQpMnYK7qut5oL7dnbFGRYmfYxAK/eiTTcMoiG/Z9NV6n6yS0lWIYi79RLOVxZ0qq4czzInst4mDQAeuyCO78u0bUyjeGZhPv+gJdTIJU/AfHtaKLWIYtDExu038FiGwyMFs/DhA4kHLS/paGLcfJqMTyywrmHiSsYBpO7O71s4B+DHEb5OhG52zOnYB/HAiHQjaEiWzB200II4NCbgRNjZqHiY0nqQ7FJIZpJ06dzNBdCPxKn0d8mRWVVio62z/Yo1cpSmoCQQKETWG8glSODQ4SC3xpdHzAIukm5uj4rV6W41KxZOSWZjgQdgzRNGLgsI5uq4hWUEEM4Xo03pRvpKqTg9ACTJlXijgUXysLBay2+VdbP7xf5SetlICUYgD7pdVWwV3a6JqGOqJ2kCnkW7KrmWv0JB7NqvDqJJJ6o0kkUsJ347XTiCCo8pp7EzTNmscN5qc/3LKJp7ZDYrpHm1TUvVeDVBrH2j0Di7hC5cQbpjTaSCgsYZda6xqO4PquhPXgwIiI4Cg0DaaHbIAFN8o8ko9Dt8Hb35aUDv5ARRGSTN44yaORsE7po=
  file: pressbooks-textbook-$TRAVIS_TAG.zip
  on:
    repo: BCcampus/pressbooks-textbook
    branch: dev
